/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.projectclothing;

import javax.swing.JOptionPane;

/**
 *
 * @author chaka
 */
public class ProjClothingOD extends javax.swing.JFrame {

    /**
     * Creates new form ProjClothingOD
     */
    public ProjClothingOD() {
        initComponents();
        shopInterf.setEnabledAt(1, false);
        shopInterf.setEnabledAt(2,false);
        ////


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopInterf = new javax.swing.JTabbedPane();
        loginPnl = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        passwrdTxt = new javax.swing.JPasswordField();
        usernameTxt = new javax.swing.JTextField();
        usernamelbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        homeppnl = new javax.swing.JScrollPane();
        homePnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logoLbl2 = new javax.swing.JLabel();
        shopppnel = new javax.swing.JScrollPane();
        shopPnl = new javax.swing.JPanel();
        aboutpnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logoLbl1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        infolbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shopInterf.setBackground(new java.awt.Color(51, 51, 51));
        shopInterf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        shopInterf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shopInterf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        loginPnl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        logoLbl.setFont(new java.awt.Font("Kindly Rewind", 0, 48)); // NOI18N
        logoLbl.setText("Delara Clothing Line Co.");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        usernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernamelbl.setText("Username");

        passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordlbl.setText("Password");

        loginBtn.setBackground(new java.awt.Color(255, 204, 153));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordlbl)
                    .addComponent(usernamelbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameTxt)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(usernamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwrdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginPnlLayout = new javax.swing.GroupLayout(loginPnl);
        loginPnl.setLayout(loginPnlLayout);
        loginPnlLayout.setHorizontalGroup(
            loginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPnlLayout.createSequentialGroup()
                .addGroup(loginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPnlLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPnlLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(logoLbl)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        loginPnlLayout.setVerticalGroup(
            loginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(logoLbl)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        shopInterf.addTab("Login", loginPnl);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        logoLbl2.setFont(new java.awt.Font("Kindly Rewind", 0, 48)); // NOI18N
        logoLbl2.setForeground(new java.awt.Color(153, 255, 255));
        logoLbl2.setText("Welcome To our Store");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(logoLbl2)
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoLbl2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePnlLayout = new javax.swing.GroupLayout(homePnl);
        homePnl.setLayout(homePnlLayout);
        homePnlLayout.setHorizontalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homePnlLayout.setVerticalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 487, Short.MAX_VALUE))
        );

        homeppnl.setViewportView(homePnl);

        shopInterf.addTab("Home", homeppnl);

        javax.swing.GroupLayout shopPnlLayout = new javax.swing.GroupLayout(shopPnl);
        shopPnl.setLayout(shopPnlLayout);
        shopPnlLayout.setHorizontalGroup(
            shopPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        shopPnlLayout.setVerticalGroup(
            shopPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        shopppnel.setViewportView(shopPnl);

        shopInterf.addTab("Shop", shopppnel);

        jLabel1.setText("<html>\n<h2> Our Team </h2>\n<ul style=\"font-size: larger;\">\n    <li>Kyla Marie Otacan</li> \n    <li>Ry Christofer Pahente</li>\n    <li>Abegail Marave</li>\n    <li>Pranz Cloma</li>\n    <li>Jeremy Tan</li>\n    <li>Jose Benito Monsanto</li>\n</ul>\n</html>");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        logoLbl1.setFont(new java.awt.Font("Kindly Rewind", 0, 48)); // NOI18N
        logoLbl1.setText("Delara Clothing Line Co.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(logoLbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoLbl1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        infolbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infolbl.setText("<html><center> Delara Clothing Line Co. is a fashion brand that creates unique and stylish clothing for men and women.  Founded with a passion for fashion and a commitment to quality, Delara Clothing Line Co.  offers a range of trendy and affordable pieces that are perfect for any occasion.  With a focus on comfort and versatility, their designs are tailored to meet the needs of modern fashion-forward individuals.  Whether you're looking for a statement piece to dress up your wardrobe or something comfortable and chic for everyday wear,  Delara Clothing Line Co. has you covered.</center> </html>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(infolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(infolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel2.setText("<html> <h2> Designers</h2> <ul style=\"font-size: larger;\">     <li>Abegail Marave</li>     <li>Pranz Cloma</li>     <li>Jose Benito Monsanto</li> <li>Kyla Marie Otacan</li> </ul> </html>");

        jLabel3.setText("<html>\n<h2> Developers</h2>\n<ul style=\"font-size: larger;\">\n    <li>Jeremy Tan</li>\n    <li>Ry Christofer Pahente</li>\n    <li>Kyla Marie Otacan</li>\n</ul>\n</html>");

        javax.swing.GroupLayout aboutpnlLayout = new javax.swing.GroupLayout(aboutpnl);
        aboutpnl.setLayout(aboutpnlLayout);
        aboutpnlLayout.setHorizontalGroup(
            aboutpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(aboutpnlLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(aboutpnlLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutpnlLayout.setVerticalGroup(
            aboutpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpnlLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(aboutpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        shopInterf.addTab("About Us", aboutpnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shopInterf, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopInterf, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String llogin = usernameTxt.getText();
        String ppaswd = new String(passwrdTxt.getPassword());

        if (llogin.equals("delara") && ppaswd.equals("delara")){
            JOptionPane.showMessageDialog(this, "Login Successful!");
            shopInterf.setEnabledAt(1, true);
            shopInterf.setEnabledAt(2,true);
            shopInterf.remove(0);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password. Please try again!");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjClothingOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjClothingOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjClothingOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjClothingOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjClothingOD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutpnl;
    private javax.swing.JPanel homePnl;
    private javax.swing.JScrollPane homeppnl;
    private javax.swing.JLabel infolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPnl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel logoLbl1;
    private javax.swing.JLabel logoLbl2;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JPasswordField passwrdTxt;
    private javax.swing.JTabbedPane shopInterf;
    private javax.swing.JPanel shopPnl;
    private javax.swing.JScrollPane shopppnel;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JLabel usernamelbl;
    // End of variables declaration//GEN-END:variables
}
